-- codes


  CREATE TABLE "SELFNOVEL"."CODES" 
   (	"MST_CD_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"DTL_CD_ID" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"MST_CD_NM" VARCHAR2(200 CHAR), 
	"DTL_CD_NM" VARCHAR2(200 CHAR), 
	"SEQ" NUMBER(7,0), 
	"SUP_MST_CD_ID" VARCHAR2(20 BYTE), 
	"USE_YN" NUMBER(1,0), 
	 CONSTRAINT "PK_CODES" PRIMARY KEY ("MST_CD_ID", "DTL_CD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SN_TBS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SN_TBS" ;
 

   COMMENT ON COLUMN "SELFNOVEL"."CODES"."MST_CD_ID" IS '마스터코드ID(PK)';
 
   COMMENT ON COLUMN "SELFNOVEL"."CODES"."DTL_CD_ID" IS '상세코드_ID(PK)';
 
   COMMENT ON COLUMN "SELFNOVEL"."CODES"."MST_CD_NM" IS '마스터코드명';
 
   COMMENT ON COLUMN "SELFNOVEL"."CODES"."DTL_CD_NM" IS '상세코드명';
 
   COMMENT ON COLUMN "SELFNOVEL"."CODES"."SEQ" IS '정렬순서';
 
   COMMENT ON COLUMN "SELFNOVEL"."CODES"."SUP_MST_CD_ID" IS '상위마스터코드ID';
 
   COMMENT ON COLUMN "SELFNOVEL"."CODES"."USE_YN" IS '사용여부';
 
   COMMENT ON TABLE "SELFNOVEL"."CODES"  IS '코드 테이블';
 
 
 
 -- expert
 
 
  CREATE TABLE "SELFNOVEL"."EXPERT" 
   (	"EXP_ID" VARCHAR2(108 BYTE), 
	"EXP_TITLE" VARCHAR2(40 CHAR) NOT NULL ENABLE, 
	"EXP_PROFILE" VARCHAR2(60 BYTE) NOT NULL ENABLE, 
	"EXP_CTG" NUMBER(2,0) NOT NULL ENABLE, 
	"EXP_PRICE" NUMBER(6,0) NOT NULL ENABLE, 
	"EXP_TRADE" NUMBER(5,0) NOT NULL ENABLE, 
	 PRIMARY KEY ("EXP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SN_TBS"  ENABLE, 
	 CONSTRAINT "FK_EXPERT" FOREIGN KEY ("EXP_ID")
	  REFERENCES "SELFNOVEL"."USERS" ("U_ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SN_TBS" ;
  
  
  
  
  -- images
  
  
  CREATE TABLE "SELFNOVEL"."IMAGES" 
   (	"IMG_ID" NUMBER NOT NULL ENABLE, 
	"IMG_NUM" NUMBER(2,0) NOT NULL ENABLE, 
	"IMG_ORG_NM" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"IMG_SV_NM" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"IMG_PATH" VARCHAR2(260 CHAR) NOT NULL ENABLE, 
	"IMG_USE_YN" NUMBER(1,0) NOT NULL ENABLE, 
	 CONSTRAINT "PK_IMAGES" PRIMARY KEY ("IMG_ID", "IMG_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SN_TBS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SN_TBS" ;
 

   COMMENT ON COLUMN "SELFNOVEL"."IMAGES"."IMG_ID" IS '이미지ID';
 
   COMMENT ON COLUMN "SELFNOVEL"."IMAGES"."IMG_NUM" IS '이미지 순서';
 
   COMMENT ON COLUMN "SELFNOVEL"."IMAGES"."IMG_ORG_NM" IS '원본 파일 이름';
 
   COMMENT ON COLUMN "SELFNOVEL"."IMAGES"."IMG_SV_NM" IS '저장 파일 이름';
 
   COMMENT ON COLUMN "SELFNOVEL"."IMAGES"."IMG_PATH" IS '파일 경로';
 
   COMMENT ON COLUMN "SELFNOVEL"."IMAGES"."IMG_USE_YN" IS '사용여부';
 
   COMMENT ON TABLE "SELFNOVEL"."IMAGES"  IS '이미지 테이블';
 

-- item


  CREATE TABLE "SELFNOVEL"."ITEM" 
   (	"RSM_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"ITM_FORM_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"ITM_PRD_ID" NUMBER(20,0), 
	"ITM_TITLE" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"ITM_CONTENT" CLOB NOT NULL ENABLE, 
	"U_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"ITM_REG_DT" DATE, 
	"ITM_SEQ" NUMBER(7,0) NOT NULL ENABLE, 
	"ITM_USE_YN" NUMBER(1,0) NOT NULL ENABLE, 
	 CONSTRAINT "ITEM_PK" PRIMARY KEY ("ITM_FORM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SN_TBS"  ENABLE, 
	 CONSTRAINT "FK_ITEM" FOREIGN KEY ("RSM_ID")
	  REFERENCES "SELFNOVEL"."RESUME" ("RSM_ID") DISABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SN_TBS" 
 LOB ("ITM_CONTENT") STORE AS BASICFILE (
  TABLESPACE "SN_TBS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
 

   COMMENT ON COLUMN "SELFNOVEL"."ITEM"."RSM_ID" IS '글 아이디';
 
   COMMENT ON COLUMN "SELFNOVEL"."ITEM"."ITM_FORM_ID" IS '항목 아이디';
 
   COMMENT ON COLUMN "SELFNOVEL"."ITEM"."ITM_PRD_ID" IS '상위항목 아이디';
 
   COMMENT ON COLUMN "SELFNOVEL"."ITEM"."ITM_TITLE" IS '소제목';
 
   COMMENT ON COLUMN "SELFNOVEL"."ITEM"."ITM_CONTENT" IS '소내용';
 
   COMMENT ON COLUMN "SELFNOVEL"."ITEM"."U_ID" IS '작성자';
 
   COMMENT ON COLUMN "SELFNOVEL"."ITEM"."ITM_REG_DT" IS '작성일';
 
   COMMENT ON COLUMN "SELFNOVEL"."ITEM"."ITM_SEQ" IS '순서';
 
   COMMENT ON COLUMN "SELFNOVEL"."ITEM"."ITM_USE_YN" IS '공개 여부';
 
   COMMENT ON TABLE "SELFNOVEL"."ITEM"  IS '첨삭 항목 테이블';
 


-- logs

  CREATE TABLE "SELFNOVEL"."LOGS" 
   (	"LOG_ID" VARCHAR2(45 BYTE) NOT NULL ENABLE, 
	"LOG_CLASS_PATH" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"LOG_SQL" CLOB, 
	"LOG_PARAM" CLOB, 
	"LOG_REG_DT" DATE NOT NULL ENABLE, 
	"LOG_REG_ID" VARCHAR2(12 BYTE), 
	"LOG_LV" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"LOG_ERRORMSG" VARCHAR2(4000 BYTE), 
	 CONSTRAINT "PK_LOGS" PRIMARY KEY ("LOG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SN_TBS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SN_TBS" 
 LOB ("LOG_SQL") STORE AS BASICFILE (
  TABLESPACE "SN_TBS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("LOG_PARAM") STORE AS BASICFILE (
  TABLESPACE "SN_TBS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
 

   COMMENT ON COLUMN "SELFNOVEL"."LOGS"."LOG_ID" IS '로그 아이디';
 
   COMMENT ON COLUMN "SELFNOVEL"."LOGS"."LOG_CLASS_PATH" IS '클래스패스';
 
   COMMENT ON COLUMN "SELFNOVEL"."LOGS"."LOG_SQL" IS 'SQL문';
 
   COMMENT ON COLUMN "SELFNOVEL"."LOGS"."LOG_PARAM" IS '파라매터';
 
   COMMENT ON COLUMN "SELFNOVEL"."LOGS"."LOG_REG_DT" IS '작성일';
 
   COMMENT ON COLUMN "SELFNOVEL"."LOGS"."LOG_REG_ID" IS '작성아이디';
 
   COMMENT ON COLUMN "SELFNOVEL"."LOGS"."LOG_LV" IS '로그레벨';
 
   COMMENT ON COLUMN "SELFNOVEL"."LOGS"."LOG_ERRORMSG" IS '에러메시지';
 
   COMMENT ON TABLE "SELFNOVEL"."LOGS"  IS '로그 테이블(옵션)';
 

-- message


  CREATE TABLE "SELFNOVEL"."MESSAGE" 
   (	"MSG_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"MSG_SENDER" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"MSG_RECEIVER" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"MSG_CONTENT" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"MSG_SEP" NUMBER(1,0) NOT NULL ENABLE, 
	"MSG_REG_DT" DATE NOT NULL ENABLE, 
	"RSM_ID" NUMBER(8,0), 
	"MSG_NOTIFY" VARCHAR2(108 BYTE), 
	"MSG_READ_YN" NUMBER(1,0) NOT NULL ENABLE, 
	"MSG_USE_YN" NUMBER(1,0) NOT NULL ENABLE, 
	 CONSTRAINT "PK_MESSAGE" PRIMARY KEY ("MSG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SN_TBS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SN_TBS" ;
 

   COMMENT ON COLUMN "SELFNOVEL"."MESSAGE"."MSG_ID" IS '메시지 아이디';
 
   COMMENT ON COLUMN "SELFNOVEL"."MESSAGE"."MSG_SENDER" IS '보내는 사람';
 
   COMMENT ON COLUMN "SELFNOVEL"."MESSAGE"."MSG_RECEIVER" IS '받는 사람';
 
   COMMENT ON COLUMN "SELFNOVEL"."MESSAGE"."MSG_CONTENT" IS '메시지 내용';
 
   COMMENT ON COLUMN "SELFNOVEL"."MESSAGE"."MSG_SEP" IS '구분';
 
   COMMENT ON COLUMN "SELFNOVEL"."MESSAGE"."MSG_REG_DT" IS '시간';
 
   COMMENT ON COLUMN "SELFNOVEL"."MESSAGE"."RSM_ID" IS '글 아이디';
 
   COMMENT ON COLUMN "SELFNOVEL"."MESSAGE"."MSG_NOTIFY" IS '신고 대상';
 
   COMMENT ON COLUMN "SELFNOVEL"."MESSAGE"."MSG_READ_YN" IS '읽음여부';
 
   COMMENT ON COLUMN "SELFNOVEL"."MESSAGE"."MSG_USE_YN" IS '사용여부';
 
   COMMENT ON TABLE "SELFNOVEL"."MESSAGE"  IS '메시지(알림) 테이블';
 


--orders


  CREATE TABLE "SELFNOVEL"."ORDERS" 
   (	"RSM_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"EXP_ID" VARCHAR2(108 BYTE) NOT NULL ENABLE, 
	"U_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"ORD_STATE" VARCHAR2(5 BYTE) NOT NULL ENABLE, 
	"ORD_REG_DT" DATE NOT NULL ENABLE, 
	"ORD_USE_YN" NUMBER(1,0) NOT NULL ENABLE, 
	 CONSTRAINT "PK_ORDERS" PRIMARY KEY ("RSM_ID", "EXP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SN_TBS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SN_TBS" ;
 

   COMMENT ON COLUMN "SELFNOVEL"."ORDERS"."RSM_ID" IS '자소서 아이디';
 
   COMMENT ON COLUMN "SELFNOVEL"."ORDERS"."EXP_ID" IS '의뢰 받은 사람';
 
   COMMENT ON COLUMN "SELFNOVEL"."ORDERS"."U_ID" IS '의뢰한 사람';
 
   COMMENT ON COLUMN "SELFNOVEL"."ORDERS"."ORD_STATE" IS '상태(코드)';
 
   COMMENT ON COLUMN "SELFNOVEL"."ORDERS"."ORD_REG_DT" IS '작성일';
 
   COMMENT ON COLUMN "SELFNOVEL"."ORDERS"."ORD_USE_YN" IS '사용 여부';
 
   COMMENT ON TABLE "SELFNOVEL"."ORDERS"  IS '의뢰 테이블';
 


--resume


  CREATE TABLE "SELFNOVEL"."RESUME" 
   (	"RSM_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"IMG_ID" NUMBER, 
	"RSM_TITLE" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"RSM_CONTENT" CLOB NOT NULL ENABLE, 
	"U_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"RSM_REG_DT" DATE NOT NULL ENABLE, 
	"RSM_COUNT" NUMBER(5,0), 
	"RSM_RECOMMEND" NUMBER(5,0), 
	"RSM_USE_YN" NUMBER(1,0) NOT NULL ENABLE, 
	"RSM_ORD_YN" NUMBER(1,0) NOT NULL ENABLE, 
	"RSM_DIV" VARCHAR2(5 BYTE), 
	 CONSTRAINT "RESUME_PK" PRIMARY KEY ("RSM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SN_TBS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SN_TBS" 
 LOB ("RSM_CONTENT") STORE AS BASICFILE (
  TABLESPACE "SN_TBS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
 

   COMMENT ON COLUMN "SELFNOVEL"."RESUME"."RSM_ID" IS '글 아이디';
 
   COMMENT ON COLUMN "SELFNOVEL"."RESUME"."IMG_ID" IS 'PPT아이디';
 
   COMMENT ON COLUMN "SELFNOVEL"."RESUME"."RSM_TITLE" IS '소제목';
 
   COMMENT ON COLUMN "SELFNOVEL"."RESUME"."RSM_CONTENT" IS '소내용';
 
   COMMENT ON COLUMN "SELFNOVEL"."RESUME"."U_ID" IS '작성자';
 
   COMMENT ON COLUMN "SELFNOVEL"."RESUME"."RSM_REG_DT" IS '작성일';
 
   COMMENT ON COLUMN "SELFNOVEL"."RESUME"."RSM_COUNT" IS '조회수';
 
   COMMENT ON COLUMN "SELFNOVEL"."RESUME"."RSM_RECOMMEND" IS '추천수';
 
   COMMENT ON COLUMN "SELFNOVEL"."RESUME"."RSM_USE_YN" IS '공개 여부';
 
   COMMENT ON COLUMN "SELFNOVEL"."RESUME"."RSM_ORD_YN" IS '신청 여부';
 
   COMMENT ON COLUMN "SELFNOVEL"."RESUME"."RSM_DIV" IS '카테고리';
 
   COMMENT ON TABLE "SELFNOVEL"."RESUME"  IS '첨삭 항목 테이블';
 


--users


  CREATE TABLE "SELFNOVEL"."USERS" 
   (	"U_ID" VARCHAR2(100 BYTE), 
	"U_PASSWORD" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"U_NAME" VARCHAR2(16 CHAR) NOT NULL ENABLE, 
	"U_REG_DT" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"U_LEVEL" NUMBER(2,0) NOT NULL ENABLE, 
	"U_WRITE_CNT" NUMBER(5,0) NOT NULL ENABLE, 
	"U_MOD_CNT" NUMBER(10,0) NOT NULL ENABLE, 
	 CONSTRAINT "PK_USERS" PRIMARY KEY ("U_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SN_TBS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SN_TBS" ;
 

   COMMENT ON COLUMN "SELFNOVEL"."USERS"."U_ID" IS '아이디(이메일)';
 
   COMMENT ON COLUMN "SELFNOVEL"."USERS"."U_PASSWORD" IS '비밀번호';
 
   COMMENT ON COLUMN "SELFNOVEL"."USERS"."U_NAME" IS '닉네임';
 
   COMMENT ON COLUMN "SELFNOVEL"."USERS"."U_REG_DT" IS '가입일';
 
   COMMENT ON COLUMN "SELFNOVEL"."USERS"."U_LEVEL" IS '등급';
 
   COMMENT ON COLUMN "SELFNOVEL"."USERS"."U_WRITE_CNT" IS '게시글 수';
 
   COMMENT ON COLUMN "SELFNOVEL"."USERS"."U_MOD_CNT" IS '첨삭 수';
 





---------------------------------------------------------------------------------------------
--시퀀스


   CREATE SEQUENCE  "SELFNOVEL"."IMG_SEQ"  MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE ;
 

   CREATE SEQUENCE  "SELFNOVEL"."ITEM_SEQ"  MINVALUE 1 MAXVALUE 5000000 INCREMENT BY 1 START WITH 281 CACHE 20 NOORDER  NOCYCLE ;
 

   CREATE SEQUENCE  "SELFNOVEL"."MSG_SEQ"  MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 521 CACHE 20 NOORDER  NOCYCLE ;
 

   CREATE SEQUENCE  "SELFNOVEL"."RESUME_SEQ"  MINVALUE 1 MAXVALUE 5000000 INCREMENT BY 1 START WITH 141 CACHE 20 NOORDER  NOCYCLE ;
 



---------------------------------------------------------------------------------------------
--함수

--GET_CD_NM
create or replace FUNCTION GET_CD_NM											
(											
	P_MST_CD_ID IN VARCHAR2,--마스터 코드										
	P_DTL_CD_ID IN VARCHAR2 --디테일코드										
											
)RETURN VARCHAR2 				--디테일코드명							
IS											
	R_DTL_CD_NM CODES.DTL_CD_NM%TYPE; --이 컬럼의 데이터타입으로 이 변수의 타입을 쓸것이다										
BEGIN											
--여기에 쿼리 줌											
	SELECT NVL(T1.DTL_CD_NM,'NONE_CODE') -- NULL이 나올경우를 대비하여										
	 INTO R_DTL_CD_NM --SELECT를 해서 나온 값을 INTO에 집어넣어라										
	 FROM CODES T1										
	WHERE T1.MST_CD_ID=P_MST_CD_ID --위에서 받았던 마스터코드 파라미터										
	  AND T1.DTL_CD_ID=P_DTL_CD_ID;										
	RETURN R_DTL_CD_NM;										
END GET_CD_NM;

--GET_RS_NM
create or replace FUNCTION GET_RS_NM
(											
	P_RSM_ID IN NUMBER--자소서 아이디								
											
)RETURN VARCHAR2 				--자소서 제목 리턴값							
IS											
	R_RSM_TITLE RESUME.RSM_TITLE%TYPE; --이 컬럼의 데이터타입으로 이 변수의 타입을 쓸것이다										
BEGIN											
--여기에 쿼리 줌											
	SELECT NVL(T1.RSM_TITLE,'NONE_CODE') -- NULL이 나올경우를 대비하여										
	 INTO R_RSM_TITLE --SELECT를 해서 나온 값을 INTO에 집어넣어라										
	 FROM RESUME T1							
	WHERE T1.RSM_ID=P_RSM_ID; --위에서 받았던 파라미터	
	RETURN R_RSM_TITLE;	
END GET_RS_NM;


--ORD_NEXT_STAT
create or replace FUNCTION ORD_NEXT_STAT
(											
	P_ORD_STATE IN VARCHAR2    --현재 상태값							
											
)RETURN VARCHAR2 											
IS											
	r_ord_state ORDERS.ord_state%TYPE; --이 컬럼의 데이터타입으로 이 변수의 타입을 쓸것이다										
BEGIN
  IF P_ORD_STATE!=10 THEN --상태값: 거절이 아니라면
    SELECT NVL(T1.NEXT_ORD_STATE,P_ORD_STATE) -- NULL이 나올경우를 대비하여. 최종단계면 최종단계 값을 준다										
     INTO r_ord_state --SELECT를 해서 나온 값을 INTO에 집어넣어라										
     FROM  
       (
        SELECT
            CODES.DTL_CD_ID AS ORD_STATE,
            LEAD(CODES.DTL_CD_ID) OVER(ORDER BY CODES.SEQ) AS NEXT_ORD_STATE
        FROM CODES
        WHERE CODES.MST_CD_ID='C001'
          AND CODES.USE_YN=1
       ) T1
    WHERE T1.ORD_STATE=P_ORD_STATE;  --위에서 받았던 파라미터	
    RETURN r_ord_state;
  ELSE --상태값: 거절이라면
    RETURN P_ORD_STATE; --현재 상태값을 그대로 반환한다
  END IF;
END ORD_NEXT_STAT;